export type LegalVariant = 'terms' | 'privacy';

export interface LegalSection {
  heading: string;
  body: string;
}

export interface LegalDocument {
  title: string;
  intro: string;
  sections: LegalSection[];
  footer: string;
}

const liabilityClause =
  'Soycraft Pet Care is an informational companion only. You agree that Soycraft, its developers, and contributing maintainers are not liable for decisions or outcomes that result from the way you interpret or rely on insights generated by the app or its AI services.';

export const LEGAL_DOCUMENTS: Record<LegalVariant, LegalDocument> = {
  terms: {
    title: 'Terms of Service',
    intro:
      'These Terms govern your use of the Soycraft Pet Care application, websites, APIs, and related services. By creating an account or using the app you consent to these Terms.',
    sections: [
      {
        heading: '1. Eligibility & Accounts',
        body:
          'You must be at least 16 years old and provide accurate information when registering. Keep your credentials secure and notify us immediately of any unauthorized access. We may suspend or terminate access if we suspect misuse.',
      },
      {
        heading: '2. Acceptable Use',
        body:
          'Only log data you have permission to share and never upload content that violates laws, infringes rights, or endangers animals. You may not reverse engineer, interfere with infrastructure, or attempt to access another user’s information.',
      },
      {
        heading: '3. Wellness Guidance Only',
        body:
          'Content, insights, and AI outputs are educational and are not veterinary or medical advice. Always consult a licensed professional for diagnoses or treatment decisions.',
      },
      {
        heading: '4. Use at Your Own Risk',
        body:
          `${liabilityClause} You acknowledge that caring for animals involves inherent risks and you remain solely responsible for assessing the suitability of any recommendations.`,
      },
      {
        heading: '5. Credits & Virtual Items',
        body:
          'Credits, rewards, and virtual perks have no cash value and may change at any time. We may revoke credits if they were earned through abuse or error.',
      },
      {
        heading: '6. Data & Intellectual Property',
        body:
          'You retain rights to the content you submit but grant Soycraft a license to store, process, and display that data to deliver the service. The app, branding, and software remain our intellectual property.',
      },
      {
        heading: '7. Termination',
        body:
          'You may delete your account at any time. We may suspend or terminate access for violations of these Terms. Upon termination you must stop using the services, but surviving clauses (e.g., liability, data rights) remain in effect.',
      },
      {
        heading: '8. Limitation of Liability',
        body:
          'To the fullest extent permitted by law, Soycraft and its developers are not liable for indirect, incidental, or consequential damages. Aggregate liability will not exceed the greater of USD $50 or the amount you paid for the service in the past six months.',
      },
    ],
    footer:
      'Contact support@soycraft.ai with questions or to request a copy of these Terms. Continued use constitutes acceptance of any future updates.',
  },
  privacy: {
    title: 'Privacy Policy',
    intro:
      'We respect your privacy and describe here how Soycraft Pet Care collects, uses, and safeguards data.',
    sections: [
      {
        heading: '1. Data We Collect',
        body:
          'We collect account details (email, profile name), pet profiles, care logs (food, supplements, stool, measurements), uploaded images, device data (such as app version and crash logs), approximate location for nearby vet lookup, and optional chat transcripts with vets or AI assistants.',
      },
      {
        heading: '2. How We Use Data',
        body:
          'Data powers core features: syncing with Supabase, generating insights, awarding rewards, and helping you export history. We also use aggregated metrics to improve reliability, detect abuse, and develop new features.',
      },
      {
        heading: '3. Sharing & Third Parties',
        body:
          'We rely on trusted processors such as Supabase for hosting, OpenAI (or similar) for AI analysis, storage providers for media, and crash/monitoring vendors. We never sell your personal information. We only disclose data to vets or caregivers you explicitly invite or when required by law.',
      },
      {
        heading: '4. Security',
        body:
          'Data is encrypted in transit and at rest within Supabase. Access is role-restricted, audit logged, and monitored. Despite safeguards, no system is perfectly secure—use strong passwords and keep your devices protected.',
      },
      {
        heading: '5. Your Choices',
        body:
          'You may update or delete data via the app, export your history from Settings, and revoke access to device features (camera, photos, location) via your OS settings. Requests for full account deletion can be sent to privacy@soycraft.ai.',
      },
      {
        heading: '6. Children & Sensitive Data',
        body:
          'We do not knowingly collect personal data from children under 16, and the service is not intended for storing human medical records. Uploaded content should only relate to pet care.',
      },
      {
        heading: '7. Contact',
        body:
          'For privacy questions or to exercise rights, email privacy@soycraft.ai. We will respond within 30 days.',
      },
    ],
    footer: liabilityClause,
  },
};
